
collections:
  members:
    output: true
    foo: bar
    years:
      - 2014
      - 2015

current_year: 2015

title: Bell Senior Society
description: "Technology & Entrepreneurship Senior Society at the University of Pennsylvania"
author:
  name: Bell Senior Society
  email: bell.senior.society@gmail.com
  github: bellsociety

production_url: http://www.bellsociety.com
exclude:
  - bin

markdown: kramdown